name: responsive_grid_list
description: A Flutter plugin to create responsive grid lists using ListView.builder() or SliverList with a SliverChildBuilderDelegate.
version: 1.0.1
publish_to: https://pub.dev
homepage: https://htoenjes.de
repository: https://github.com/hauketoenjes/responsive_grid_list
issue_tracker: https://github.com/hauketoenjes/responsive_grid_list/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  quiver: ^2.1.5
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0

flutter: