name: responsive_grid_list
description: Flutter plugin to create responsive grid lists
version: 0.0.1
author: Hauke Tönjes
homepage: htoenjes.de

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  quiver: ^2.1.5
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0

flutter: